name: 'Token Who Am I'
description: 'Retrieve identity information behind the GitHub token'
inputs:
  github-token:
    description: 'GitHub token.'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'users'
  color: 'gray-dark'
